# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import brain_pb2 as brain__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2



class BrainServiceStub(object):
    """Brain v2 CRUD Service
    Postgres-first storage for KGRAG knowledge entities with Kafka async enrichment.
    Co-hosted with CogneeService on the same gRPC server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateKnowledge = channel.unary_unary(
                '/kgrag.brain.BrainService/CreateKnowledge',
                request_serializer=brain__pb2.CreateKnowledgeRequest.SerializeToString,
                response_deserializer=brain__pb2.KnowledgeResponse.FromString,
                _registered_method=True)
        self.GetKnowledge = channel.unary_unary(
                '/kgrag.brain.BrainService/GetKnowledge',
                request_serializer=brain__pb2.GetByIdRequest.SerializeToString,
                response_deserializer=brain__pb2.KnowledgeResponse.FromString,
                _registered_method=True)
        self.ListKnowledge = channel.unary_unary(
                '/kgrag.brain.BrainService/ListKnowledge',
                request_serializer=brain__pb2.ListKnowledgeRequest.SerializeToString,
                response_deserializer=brain__pb2.ListKnowledgeResponse.FromString,
                _registered_method=True)
        self.UpdateKnowledge = channel.unary_unary(
                '/kgrag.brain.BrainService/UpdateKnowledge',
                request_serializer=brain__pb2.UpdateKnowledgeRequest.SerializeToString,
                response_deserializer=brain__pb2.KnowledgeResponse.FromString,
                _registered_method=True)
        self.DeleteKnowledge = channel.unary_unary(
                '/kgrag.brain.BrainService/DeleteKnowledge',
                request_serializer=brain__pb2.DeleteByIdRequest.SerializeToString,
                response_deserializer=brain__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.CreateExpertise = channel.unary_unary(
                '/kgrag.brain.BrainService/CreateExpertise',
                request_serializer=brain__pb2.CreateExpertiseRequest.SerializeToString,
                response_deserializer=brain__pb2.ExpertiseResponse.FromString,
                _registered_method=True)
        self.GetExpertise = channel.unary_unary(
                '/kgrag.brain.BrainService/GetExpertise',
                request_serializer=brain__pb2.GetByIdRequest.SerializeToString,
                response_deserializer=brain__pb2.ExpertiseResponse.FromString,
                _registered_method=True)
        self.ListExpertise = channel.unary_unary(
                '/kgrag.brain.BrainService/ListExpertise',
                request_serializer=brain__pb2.ListExpertiseRequest.SerializeToString,
                response_deserializer=brain__pb2.ListExpertiseResponse.FromString,
                _registered_method=True)
        self.UpdateExpertise = channel.unary_unary(
                '/kgrag.brain.BrainService/UpdateExpertise',
                request_serializer=brain__pb2.UpdateExpertiseRequest.SerializeToString,
                response_deserializer=brain__pb2.ExpertiseResponse.FromString,
                _registered_method=True)
        self.DeleteExpertise = channel.unary_unary(
                '/kgrag.brain.BrainService/DeleteExpertise',
                request_serializer=brain__pb2.DeleteByIdRequest.SerializeToString,
                response_deserializer=brain__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.AddExpertiseChunk = channel.unary_unary(
                '/kgrag.brain.BrainService/AddExpertiseChunk',
                request_serializer=brain__pb2.AddExpertiseChunkRequest.SerializeToString,
                response_deserializer=brain__pb2.ExpertiseChunkResponse.FromString,
                _registered_method=True)
        self.LinkExpertiseToAgent = channel.unary_unary(
                '/kgrag.brain.BrainService/LinkExpertiseToAgent',
                request_serializer=brain__pb2.LinkRequest.SerializeToString,
                response_deserializer=brain__pb2.LinkResponse.FromString,
                _registered_method=True)
        self.UnlinkExpertiseFromAgent = channel.unary_unary(
                '/kgrag.brain.BrainService/UnlinkExpertiseFromAgent',
                request_serializer=brain__pb2.LinkRequest.SerializeToString,
                response_deserializer=brain__pb2.LinkResponse.FromString,
                _registered_method=True)
        self.RecordLesson = channel.unary_unary(
                '/kgrag.brain.BrainService/RecordLesson',
                request_serializer=brain__pb2.RecordLessonRequest.SerializeToString,
                response_deserializer=brain__pb2.LessonResponse.FromString,
                _registered_method=True)
        self.GetLesson = channel.unary_unary(
                '/kgrag.brain.BrainService/GetLesson',
                request_serializer=brain__pb2.GetByIdRequest.SerializeToString,
                response_deserializer=brain__pb2.LessonResponse.FromString,
                _registered_method=True)
        self.ListLessons = channel.unary_unary(
                '/kgrag.brain.BrainService/ListLessons',
                request_serializer=brain__pb2.ListLessonsRequest.SerializeToString,
                response_deserializer=brain__pb2.ListLessonsResponse.FromString,
                _registered_method=True)
        self.UpdateLesson = channel.unary_unary(
                '/kgrag.brain.BrainService/UpdateLesson',
                request_serializer=brain__pb2.UpdateLessonRequest.SerializeToString,
                response_deserializer=brain__pb2.LessonResponse.FromString,
                _registered_method=True)
        self.DeleteLesson = channel.unary_unary(
                '/kgrag.brain.BrainService/DeleteLesson',
                request_serializer=brain__pb2.DeleteByIdRequest.SerializeToString,
                response_deserializer=brain__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.CreateEngagement = channel.unary_unary(
                '/kgrag.brain.BrainService/CreateEngagement',
                request_serializer=brain__pb2.CreateEngagementRequest.SerializeToString,
                response_deserializer=brain__pb2.EngagementResponse.FromString,
                _registered_method=True)
        self.GetEngagement = channel.unary_unary(
                '/kgrag.brain.BrainService/GetEngagement',
                request_serializer=brain__pb2.GetByIdRequest.SerializeToString,
                response_deserializer=brain__pb2.EngagementResponse.FromString,
                _registered_method=True)
        self.ListEngagements = channel.unary_unary(
                '/kgrag.brain.BrainService/ListEngagements',
                request_serializer=brain__pb2.ListEngagementsRequest.SerializeToString,
                response_deserializer=brain__pb2.ListEngagementsResponse.FromString,
                _registered_method=True)
        self.UpdateEngagement = channel.unary_unary(
                '/kgrag.brain.BrainService/UpdateEngagement',
                request_serializer=brain__pb2.UpdateEngagementRequest.SerializeToString,
                response_deserializer=brain__pb2.EngagementResponse.FromString,
                _registered_method=True)
        self.DeleteEngagement = channel.unary_unary(
                '/kgrag.brain.BrainService/DeleteEngagement',
                request_serializer=brain__pb2.GetByIdRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AddEntry = channel.unary_unary(
                '/kgrag.brain.BrainService/AddEntry',
                request_serializer=brain__pb2.AddEntryRequest.SerializeToString,
                response_deserializer=brain__pb2.EntryResponse.FromString,
                _registered_method=True)
        self.GetEntry = channel.unary_unary(
                '/kgrag.brain.BrainService/GetEntry',
                request_serializer=brain__pb2.GetByIdRequest.SerializeToString,
                response_deserializer=brain__pb2.EntryResponse.FromString,
                _registered_method=True)
        self.ListEntries = channel.unary_unary(
                '/kgrag.brain.BrainService/ListEntries',
                request_serializer=brain__pb2.ListEntriesRequest.SerializeToString,
                response_deserializer=brain__pb2.ListEntriesResponse.FromString,
                _registered_method=True)
        self.UpdateEntry = channel.unary_unary(
                '/kgrag.brain.BrainService/UpdateEntry',
                request_serializer=brain__pb2.UpdateEntryRequest.SerializeToString,
                response_deserializer=brain__pb2.EntryResponse.FromString,
                _registered_method=True)
        self.DeleteEntry = channel.unary_unary(
                '/kgrag.brain.BrainService/DeleteEntry',
                request_serializer=brain__pb2.GetByIdRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SearchEntries = channel.unary_unary(
                '/kgrag.brain.BrainService/SearchEntries',
                request_serializer=brain__pb2.SearchEntriesRequest.SerializeToString,
                response_deserializer=brain__pb2.ListEntriesResponse.FromString,
                _registered_method=True)
        self.ResumeEngagement = channel.unary_unary(
                '/kgrag.brain.BrainService/ResumeEngagement',
                request_serializer=brain__pb2.GetByIdRequest.SerializeToString,
                response_deserializer=brain__pb2.ResumeEngagementResponse.FromString,
                _registered_method=True)
        self.UnifiedSearch = channel.unary_unary(
                '/kgrag.brain.BrainService/UnifiedSearch',
                request_serializer=brain__pb2.UnifiedSearchRequest.SerializeToString,
                response_deserializer=brain__pb2.UnifiedSearchResponse.FromString,
                _registered_method=True)


class BrainServiceServicer(object):
    """Brain v2 CRUD Service
    Postgres-first storage for KGRAG knowledge entities with Kafka async enrichment.
    Co-hosted with CogneeService on the same gRPC server.
    """

    def CreateKnowledge(self, request, context):
        """── Knowledge ───────────────────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateExpertise(self, request, context):
        """── Expertise ──────────────────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExpertise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExpertise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateExpertise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteExpertise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddExpertiseChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LinkExpertiseToAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlinkExpertiseFromAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordLesson(self, request, context):
        """── Lessons ────────────────────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLesson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLessons(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLesson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLesson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEngagement(self, request, context):
        """── Engagements ────────────────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEngagement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEngagements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEngagement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEngagement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddEntry(self, request, context):
        """── Entries ────────────────────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeEngagement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnifiedSearch(self, request, context):
        """── Search ─────────────────────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateKnowledge,
                    request_deserializer=brain__pb2.CreateKnowledgeRequest.FromString,
                    response_serializer=brain__pb2.KnowledgeResponse.SerializeToString,
            ),
            'GetKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKnowledge,
                    request_deserializer=brain__pb2.GetByIdRequest.FromString,
                    response_serializer=brain__pb2.KnowledgeResponse.SerializeToString,
            ),
            'ListKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.ListKnowledge,
                    request_deserializer=brain__pb2.ListKnowledgeRequest.FromString,
                    response_serializer=brain__pb2.ListKnowledgeResponse.SerializeToString,
            ),
            'UpdateKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateKnowledge,
                    request_deserializer=brain__pb2.UpdateKnowledgeRequest.FromString,
                    response_serializer=brain__pb2.KnowledgeResponse.SerializeToString,
            ),
            'DeleteKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKnowledge,
                    request_deserializer=brain__pb2.DeleteByIdRequest.FromString,
                    response_serializer=brain__pb2.DeleteResponse.SerializeToString,
            ),
            'CreateExpertise': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateExpertise,
                    request_deserializer=brain__pb2.CreateExpertiseRequest.FromString,
                    response_serializer=brain__pb2.ExpertiseResponse.SerializeToString,
            ),
            'GetExpertise': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExpertise,
                    request_deserializer=brain__pb2.GetByIdRequest.FromString,
                    response_serializer=brain__pb2.ExpertiseResponse.SerializeToString,
            ),
            'ListExpertise': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExpertise,
                    request_deserializer=brain__pb2.ListExpertiseRequest.FromString,
                    response_serializer=brain__pb2.ListExpertiseResponse.SerializeToString,
            ),
            'UpdateExpertise': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateExpertise,
                    request_deserializer=brain__pb2.UpdateExpertiseRequest.FromString,
                    response_serializer=brain__pb2.ExpertiseResponse.SerializeToString,
            ),
            'DeleteExpertise': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteExpertise,
                    request_deserializer=brain__pb2.DeleteByIdRequest.FromString,
                    response_serializer=brain__pb2.DeleteResponse.SerializeToString,
            ),
            'AddExpertiseChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.AddExpertiseChunk,
                    request_deserializer=brain__pb2.AddExpertiseChunkRequest.FromString,
                    response_serializer=brain__pb2.ExpertiseChunkResponse.SerializeToString,
            ),
            'LinkExpertiseToAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.LinkExpertiseToAgent,
                    request_deserializer=brain__pb2.LinkRequest.FromString,
                    response_serializer=brain__pb2.LinkResponse.SerializeToString,
            ),
            'UnlinkExpertiseFromAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlinkExpertiseFromAgent,
                    request_deserializer=brain__pb2.LinkRequest.FromString,
                    response_serializer=brain__pb2.LinkResponse.SerializeToString,
            ),
            'RecordLesson': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordLesson,
                    request_deserializer=brain__pb2.RecordLessonRequest.FromString,
                    response_serializer=brain__pb2.LessonResponse.SerializeToString,
            ),
            'GetLesson': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLesson,
                    request_deserializer=brain__pb2.GetByIdRequest.FromString,
                    response_serializer=brain__pb2.LessonResponse.SerializeToString,
            ),
            'ListLessons': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLessons,
                    request_deserializer=brain__pb2.ListLessonsRequest.FromString,
                    response_serializer=brain__pb2.ListLessonsResponse.SerializeToString,
            ),
            'UpdateLesson': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLesson,
                    request_deserializer=brain__pb2.UpdateLessonRequest.FromString,
                    response_serializer=brain__pb2.LessonResponse.SerializeToString,
            ),
            'DeleteLesson': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLesson,
                    request_deserializer=brain__pb2.DeleteByIdRequest.FromString,
                    response_serializer=brain__pb2.DeleteResponse.SerializeToString,
            ),
            'CreateEngagement': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEngagement,
                    request_deserializer=brain__pb2.CreateEngagementRequest.FromString,
                    response_serializer=brain__pb2.EngagementResponse.SerializeToString,
            ),
            'GetEngagement': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEngagement,
                    request_deserializer=brain__pb2.GetByIdRequest.FromString,
                    response_serializer=brain__pb2.EngagementResponse.SerializeToString,
            ),
            'ListEngagements': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEngagements,
                    request_deserializer=brain__pb2.ListEngagementsRequest.FromString,
                    response_serializer=brain__pb2.ListEngagementsResponse.SerializeToString,
            ),
            'UpdateEngagement': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEngagement,
                    request_deserializer=brain__pb2.UpdateEngagementRequest.FromString,
                    response_serializer=brain__pb2.EngagementResponse.SerializeToString,
            ),
            'DeleteEngagement': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEngagement,
                    request_deserializer=brain__pb2.GetByIdRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AddEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.AddEntry,
                    request_deserializer=brain__pb2.AddEntryRequest.FromString,
                    response_serializer=brain__pb2.EntryResponse.SerializeToString,
            ),
            'GetEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntry,
                    request_deserializer=brain__pb2.GetByIdRequest.FromString,
                    response_serializer=brain__pb2.EntryResponse.SerializeToString,
            ),
            'ListEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEntries,
                    request_deserializer=brain__pb2.ListEntriesRequest.FromString,
                    response_serializer=brain__pb2.ListEntriesResponse.SerializeToString,
            ),
            'UpdateEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEntry,
                    request_deserializer=brain__pb2.UpdateEntryRequest.FromString,
                    response_serializer=brain__pb2.EntryResponse.SerializeToString,
            ),
            'DeleteEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEntry,
                    request_deserializer=brain__pb2.GetByIdRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SearchEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchEntries,
                    request_deserializer=brain__pb2.SearchEntriesRequest.FromString,
                    response_serializer=brain__pb2.ListEntriesResponse.SerializeToString,
            ),
            'ResumeEngagement': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeEngagement,
                    request_deserializer=brain__pb2.GetByIdRequest.FromString,
                    response_serializer=brain__pb2.ResumeEngagementResponse.SerializeToString,
            ),
            'UnifiedSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.UnifiedSearch,
                    request_deserializer=brain__pb2.UnifiedSearchRequest.FromString,
                    response_serializer=brain__pb2.UnifiedSearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kgrag.brain.BrainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kgrag.brain.BrainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrainService(object):
    """Brain v2 CRUD Service
    Postgres-first storage for KGRAG knowledge entities with Kafka async enrichment.
    Co-hosted with CogneeService on the same gRPC server.
    """

    @staticmethod
    def CreateKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/CreateKnowledge',
            brain__pb2.CreateKnowledgeRequest.SerializeToString,
            brain__pb2.KnowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/GetKnowledge',
            brain__pb2.GetByIdRequest.SerializeToString,
            brain__pb2.KnowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/ListKnowledge',
            brain__pb2.ListKnowledgeRequest.SerializeToString,
            brain__pb2.ListKnowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/UpdateKnowledge',
            brain__pb2.UpdateKnowledgeRequest.SerializeToString,
            brain__pb2.KnowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/DeleteKnowledge',
            brain__pb2.DeleteByIdRequest.SerializeToString,
            brain__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateExpertise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/CreateExpertise',
            brain__pb2.CreateExpertiseRequest.SerializeToString,
            brain__pb2.ExpertiseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExpertise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/GetExpertise',
            brain__pb2.GetByIdRequest.SerializeToString,
            brain__pb2.ExpertiseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListExpertise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/ListExpertise',
            brain__pb2.ListExpertiseRequest.SerializeToString,
            brain__pb2.ListExpertiseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateExpertise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/UpdateExpertise',
            brain__pb2.UpdateExpertiseRequest.SerializeToString,
            brain__pb2.ExpertiseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteExpertise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/DeleteExpertise',
            brain__pb2.DeleteByIdRequest.SerializeToString,
            brain__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddExpertiseChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/AddExpertiseChunk',
            brain__pb2.AddExpertiseChunkRequest.SerializeToString,
            brain__pb2.ExpertiseChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LinkExpertiseToAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/LinkExpertiseToAgent',
            brain__pb2.LinkRequest.SerializeToString,
            brain__pb2.LinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlinkExpertiseFromAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/UnlinkExpertiseFromAgent',
            brain__pb2.LinkRequest.SerializeToString,
            brain__pb2.LinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordLesson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/RecordLesson',
            brain__pb2.RecordLessonRequest.SerializeToString,
            brain__pb2.LessonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLesson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/GetLesson',
            brain__pb2.GetByIdRequest.SerializeToString,
            brain__pb2.LessonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLessons(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/ListLessons',
            brain__pb2.ListLessonsRequest.SerializeToString,
            brain__pb2.ListLessonsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLesson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/UpdateLesson',
            brain__pb2.UpdateLessonRequest.SerializeToString,
            brain__pb2.LessonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteLesson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/DeleteLesson',
            brain__pb2.DeleteByIdRequest.SerializeToString,
            brain__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEngagement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/CreateEngagement',
            brain__pb2.CreateEngagementRequest.SerializeToString,
            brain__pb2.EngagementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEngagement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/GetEngagement',
            brain__pb2.GetByIdRequest.SerializeToString,
            brain__pb2.EngagementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEngagements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/ListEngagements',
            brain__pb2.ListEngagementsRequest.SerializeToString,
            brain__pb2.ListEngagementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEngagement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/UpdateEngagement',
            brain__pb2.UpdateEngagementRequest.SerializeToString,
            brain__pb2.EngagementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEngagement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/DeleteEngagement',
            brain__pb2.GetByIdRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/AddEntry',
            brain__pb2.AddEntryRequest.SerializeToString,
            brain__pb2.EntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/GetEntry',
            brain__pb2.GetByIdRequest.SerializeToString,
            brain__pb2.EntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/ListEntries',
            brain__pb2.ListEntriesRequest.SerializeToString,
            brain__pb2.ListEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/UpdateEntry',
            brain__pb2.UpdateEntryRequest.SerializeToString,
            brain__pb2.EntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/DeleteEntry',
            brain__pb2.GetByIdRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/SearchEntries',
            brain__pb2.SearchEntriesRequest.SerializeToString,
            brain__pb2.ListEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeEngagement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/ResumeEngagement',
            brain__pb2.GetByIdRequest.SerializeToString,
            brain__pb2.ResumeEngagementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnifiedSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainService/UnifiedSearch',
            brain__pb2.UnifiedSearchRequest.SerializeToString,
            brain__pb2.UnifiedSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BrainContentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddToBrain = channel.unary_unary(
                '/kgrag.brain.BrainContentService/AddToBrain',
                request_serializer=brain__pb2.AddToBrainRequest.SerializeToString,
                response_deserializer=brain__pb2.BrainContentResponse.FromString,
                _registered_method=True)
        self.UpdateBrain = channel.unary_unary(
                '/kgrag.brain.BrainContentService/UpdateBrain',
                request_serializer=brain__pb2.UpdateBrainRequest.SerializeToString,
                response_deserializer=brain__pb2.BrainContentResponse.FromString,
                _registered_method=True)
        self.DeleteFromBrain = channel.unary_unary(
                '/kgrag.brain.BrainContentService/DeleteFromBrain',
                request_serializer=brain__pb2.DeleteFromBrainRequest.SerializeToString,
                response_deserializer=brain__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.GetBrainContent = channel.unary_unary(
                '/kgrag.brain.BrainContentService/GetBrainContent',
                request_serializer=brain__pb2.GetBrainContentRequest.SerializeToString,
                response_deserializer=brain__pb2.BrainContentResponse.FromString,
                _registered_method=True)
        self.ListBrainContent = channel.unary_unary(
                '/kgrag.brain.BrainContentService/ListBrainContent',
                request_serializer=brain__pb2.ListBrainContentRequest.SerializeToString,
                response_deserializer=brain__pb2.ListBrainContentResponse.FromString,
                _registered_method=True)


class BrainContentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddToBrain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBrain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFromBrain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBrainContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBrainContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrainContentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddToBrain': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToBrain,
                    request_deserializer=brain__pb2.AddToBrainRequest.FromString,
                    response_serializer=brain__pb2.BrainContentResponse.SerializeToString,
            ),
            'UpdateBrain': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBrain,
                    request_deserializer=brain__pb2.UpdateBrainRequest.FromString,
                    response_serializer=brain__pb2.BrainContentResponse.SerializeToString,
            ),
            'DeleteFromBrain': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFromBrain,
                    request_deserializer=brain__pb2.DeleteFromBrainRequest.FromString,
                    response_serializer=brain__pb2.DeleteResponse.SerializeToString,
            ),
            'GetBrainContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBrainContent,
                    request_deserializer=brain__pb2.GetBrainContentRequest.FromString,
                    response_serializer=brain__pb2.BrainContentResponse.SerializeToString,
            ),
            'ListBrainContent': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBrainContent,
                    request_deserializer=brain__pb2.ListBrainContentRequest.FromString,
                    response_serializer=brain__pb2.ListBrainContentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kgrag.brain.BrainContentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kgrag.brain.BrainContentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrainContentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddToBrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainContentService/AddToBrain',
            brain__pb2.AddToBrainRequest.SerializeToString,
            brain__pb2.BrainContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainContentService/UpdateBrain',
            brain__pb2.UpdateBrainRequest.SerializeToString,
            brain__pb2.BrainContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFromBrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainContentService/DeleteFromBrain',
            brain__pb2.DeleteFromBrainRequest.SerializeToString,
            brain__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBrainContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainContentService/GetBrainContent',
            brain__pb2.GetBrainContentRequest.SerializeToString,
            brain__pb2.BrainContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBrainContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.brain.BrainContentService/ListBrainContent',
            brain__pb2.ListBrainContentRequest.SerializeToString,
            brain__pb2.ListBrainContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
