# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cognee_pb2 as cognee__pb2



class CogneeServiceStub(object):
    """Cognee Knowledge Enrichment Service
    Standalone gRPC microservice for graph-based knowledge enrichment via cognee.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Cognify = channel.unary_unary(
                '/kgrag.cognee.CogneeService/Cognify',
                request_serializer=cognee__pb2.CognifyRequest.SerializeToString,
                response_deserializer=cognee__pb2.CognifyResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/kgrag.cognee.CogneeService/Search',
                request_serializer=cognee__pb2.SearchRequest.SerializeToString,
                response_deserializer=cognee__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.FlexibleCogneeSearch = channel.unary_unary(
                '/kgrag.cognee.CogneeService/FlexibleCogneeSearch',
                request_serializer=cognee__pb2.FlexibleCogneeSearchRequest.SerializeToString,
                response_deserializer=cognee__pb2.FlexibleCogneeSearchResponse.FromString,
                _registered_method=True)
        self.FlexibleCodeSearch = channel.unary_unary(
                '/kgrag.cognee.CogneeService/FlexibleCodeSearch',
                request_serializer=cognee__pb2.FlexibleCodeSearchRequest.SerializeToString,
                response_deserializer=cognee__pb2.FlexibleCodeSearchResponse.FromString,
                _registered_method=True)
        self.Prune = channel.unary_unary(
                '/kgrag.cognee.CogneeService/Prune',
                request_serializer=cognee__pb2.PruneRequest.SerializeToString,
                response_deserializer=cognee__pb2.PruneResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/kgrag.cognee.CogneeService/Health',
                request_serializer=cognee__pb2.HealthRequest.SerializeToString,
                response_deserializer=cognee__pb2.HealthResponse.FromString,
                _registered_method=True)


class CogneeServiceServicer(object):
    """Cognee Knowledge Enrichment Service
    Standalone gRPC microservice for graph-based knowledge enrichment via cognee.
    """

    def Cognify(self, request, context):
        """Add text to a dataset and run cognify (graph enrichment)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Search the cognee knowledge graph
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FlexibleCogneeSearch(self, request, context):
        """Flexible knowledge-only search
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FlexibleCodeSearch(self, request, context):
        """Flexible code-only search
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prune(self, request, context):
        """Prune (delete) a dataset from the knowledge graph
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CogneeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Cognify': grpc.unary_unary_rpc_method_handler(
                    servicer.Cognify,
                    request_deserializer=cognee__pb2.CognifyRequest.FromString,
                    response_serializer=cognee__pb2.CognifyResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=cognee__pb2.SearchRequest.FromString,
                    response_serializer=cognee__pb2.SearchResponse.SerializeToString,
            ),
            'FlexibleCogneeSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.FlexibleCogneeSearch,
                    request_deserializer=cognee__pb2.FlexibleCogneeSearchRequest.FromString,
                    response_serializer=cognee__pb2.FlexibleCogneeSearchResponse.SerializeToString,
            ),
            'FlexibleCodeSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.FlexibleCodeSearch,
                    request_deserializer=cognee__pb2.FlexibleCodeSearchRequest.FromString,
                    response_serializer=cognee__pb2.FlexibleCodeSearchResponse.SerializeToString,
            ),
            'Prune': grpc.unary_unary_rpc_method_handler(
                    servicer.Prune,
                    request_deserializer=cognee__pb2.PruneRequest.FromString,
                    response_serializer=cognee__pb2.PruneResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=cognee__pb2.HealthRequest.FromString,
                    response_serializer=cognee__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kgrag.cognee.CogneeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kgrag.cognee.CogneeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CogneeService(object):
    """Cognee Knowledge Enrichment Service
    Standalone gRPC microservice for graph-based knowledge enrichment via cognee.
    """

    @staticmethod
    def Cognify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.cognee.CogneeService/Cognify',
            cognee__pb2.CognifyRequest.SerializeToString,
            cognee__pb2.CognifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.cognee.CogneeService/Search',
            cognee__pb2.SearchRequest.SerializeToString,
            cognee__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FlexibleCogneeSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.cognee.CogneeService/FlexibleCogneeSearch',
            cognee__pb2.FlexibleCogneeSearchRequest.SerializeToString,
            cognee__pb2.FlexibleCogneeSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FlexibleCodeSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.cognee.CogneeService/FlexibleCodeSearch',
            cognee__pb2.FlexibleCodeSearchRequest.SerializeToString,
            cognee__pb2.FlexibleCodeSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Prune(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.cognee.CogneeService/Prune',
            cognee__pb2.PruneRequest.SerializeToString,
            cognee__pb2.PruneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.cognee.CogneeService/Health',
            cognee__pb2.HealthRequest.SerializeToString,
            cognee__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
