# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\nkgrag.auth\".\n\x0b\x41uthRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x98\x01\n\x0c\x41uthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\x12\x15\n\rrefresh_token\x18\x03 \x01(\t\x12\x12\n\ntoken_type\x18\x04 \x01(\t\x12\x12\n\nexpires_in\x18\x05 \x01(\x05\x12\x12\n\nuser_email\x18\x06 \x01(\t\x12\x0f\n\x07message\x18\x07 \x01(\t\"(\n\x12GetProjectsRequest\x12\x12\n\nuser_token\x18\x01 \x01(\t\"~\n\x0bProjectItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\ncompany_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x05 \x01(\t\x12\x16\n\x0e\x63ognee_enabled\x18\x06 \x01(\x08\"\x8d\x01\n\x13GetProjectsResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0eprojects_count\x18\x03 \x01(\x05\x12)\n\x08projects\x18\x04 \x03(\x0b\x32\x17.kgrag.auth.ProjectItem\x12\x12\n\nuser_email\x18\x05 \x01(\t2\xa0\x01\n\x0b\x41uthService\x12\x41\n\x0c\x41uthenticate\x12\x17.kgrag.auth.AuthRequest\x1a\x18.kgrag.auth.AuthResponse\x12N\n\x0bGetProjects\x12\x1e.kgrag.auth.GetProjectsRequest\x1a\x1f.kgrag.auth.GetProjectsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQUEST']._serialized_start=26
  _globals['_AUTHREQUEST']._serialized_end=72
  _globals['_AUTHRESPONSE']._serialized_start=75
  _globals['_AUTHRESPONSE']._serialized_end=227
  _globals['_GETPROJECTSREQUEST']._serialized_start=229
  _globals['_GETPROJECTSREQUEST']._serialized_end=269
  _globals['_PROJECTITEM']._serialized_start=271
  _globals['_PROJECTITEM']._serialized_end=397
  _globals['_GETPROJECTSRESPONSE']._serialized_start=400
  _globals['_GETPROJECTSRESPONSE']._serialized_end=541
  _globals['_AUTHSERVICE']._serialized_start=544
  _globals['_AUTHSERVICE']._serialized_end=704
# @@protoc_insertion_point(module_scope)
