# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import code_search_pb2 as code__search__pb2



class CodeSearchServiceStub(object):
    """Code Search Service — six atomic primitives + FullSearch composite + Health.
    7 unary RPCs only. No LLM dependency on the backend.
    Agentic search runs in the MCP tool layer (kgrag-mcp/tools/code_search.py).

    Tenancy: company_id is derived server-side from the JWT. The client MUST NOT
    supply a company_id — the field was removed in T10.A.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDomains = channel.unary_unary(
                '/kgrag.code_search.CodeSearchService/GetDomains',
                request_serializer=code__search__pb2.GetDomainsRequest.SerializeToString,
                response_deserializer=code__search__pb2.GetDomainsResponse.FromString,
                _registered_method=True)
        self.SearchEntities = channel.unary_unary(
                '/kgrag.code_search.CodeSearchService/SearchEntities',
                request_serializer=code__search__pb2.SearchEntitiesRequest.SerializeToString,
                response_deserializer=code__search__pb2.SearchEntitiesResponse.FromString,
                _registered_method=True)
        self.SearchSummaries = channel.unary_unary(
                '/kgrag.code_search.CodeSearchService/SearchSummaries',
                request_serializer=code__search__pb2.SearchSummariesRequest.SerializeToString,
                response_deserializer=code__search__pb2.SearchSummariesResponse.FromString,
                _registered_method=True)
        self.GetCodeForEntity = channel.unary_unary(
                '/kgrag.code_search.CodeSearchService/GetCodeForEntity',
                request_serializer=code__search__pb2.GetCodeForEntityRequest.SerializeToString,
                response_deserializer=code__search__pb2.GetCodeForEntityResponse.FromString,
                _registered_method=True)
        self.TraverseGraph = channel.unary_unary(
                '/kgrag.code_search.CodeSearchService/TraverseGraph',
                request_serializer=code__search__pb2.TraverseGraphRequest.SerializeToString,
                response_deserializer=code__search__pb2.TraverseGraphResponse.FromString,
                _registered_method=True)
        self.GetEntityGraph = channel.unary_unary(
                '/kgrag.code_search.CodeSearchService/GetEntityGraph',
                request_serializer=code__search__pb2.GetEntityGraphRequest.SerializeToString,
                response_deserializer=code__search__pb2.GetEntityGraphResponse.FromString,
                _registered_method=True)
        self.FullSearch = channel.unary_unary(
                '/kgrag.code_search.CodeSearchService/FullSearch',
                request_serializer=code__search__pb2.FullSearchRequest.SerializeToString,
                response_deserializer=code__search__pb2.FullSearchResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/kgrag.code_search.CodeSearchService/Health',
                request_serializer=code__search__pb2.HealthRequest.SerializeToString,
                response_deserializer=code__search__pb2.HealthResponse.FromString,
                _registered_method=True)


class CodeSearchServiceServicer(object):
    """Code Search Service — six atomic primitives + FullSearch composite + Health.
    7 unary RPCs only. No LLM dependency on the backend.
    Agentic search runs in the MCP tool layer (kgrag-mcp/tools/code_search.py).

    Tenancy: company_id is derived server-side from the JWT. The client MUST NOT
    supply a company_id — the field was removed in T10.A.
    """

    def GetDomains(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchEntities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchSummaries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCodeForEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TraverseGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntityGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FullSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodeSearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDomains': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDomains,
                    request_deserializer=code__search__pb2.GetDomainsRequest.FromString,
                    response_serializer=code__search__pb2.GetDomainsResponse.SerializeToString,
            ),
            'SearchEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchEntities,
                    request_deserializer=code__search__pb2.SearchEntitiesRequest.FromString,
                    response_serializer=code__search__pb2.SearchEntitiesResponse.SerializeToString,
            ),
            'SearchSummaries': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchSummaries,
                    request_deserializer=code__search__pb2.SearchSummariesRequest.FromString,
                    response_serializer=code__search__pb2.SearchSummariesResponse.SerializeToString,
            ),
            'GetCodeForEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCodeForEntity,
                    request_deserializer=code__search__pb2.GetCodeForEntityRequest.FromString,
                    response_serializer=code__search__pb2.GetCodeForEntityResponse.SerializeToString,
            ),
            'TraverseGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.TraverseGraph,
                    request_deserializer=code__search__pb2.TraverseGraphRequest.FromString,
                    response_serializer=code__search__pb2.TraverseGraphResponse.SerializeToString,
            ),
            'GetEntityGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntityGraph,
                    request_deserializer=code__search__pb2.GetEntityGraphRequest.FromString,
                    response_serializer=code__search__pb2.GetEntityGraphResponse.SerializeToString,
            ),
            'FullSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.FullSearch,
                    request_deserializer=code__search__pb2.FullSearchRequest.FromString,
                    response_serializer=code__search__pb2.FullSearchResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=code__search__pb2.HealthRequest.FromString,
                    response_serializer=code__search__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kgrag.code_search.CodeSearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kgrag.code_search.CodeSearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CodeSearchService(object):
    """Code Search Service — six atomic primitives + FullSearch composite + Health.
    7 unary RPCs only. No LLM dependency on the backend.
    Agentic search runs in the MCP tool layer (kgrag-mcp/tools/code_search.py).

    Tenancy: company_id is derived server-side from the JWT. The client MUST NOT
    supply a company_id — the field was removed in T10.A.
    """

    @staticmethod
    def GetDomains(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.code_search.CodeSearchService/GetDomains',
            code__search__pb2.GetDomainsRequest.SerializeToString,
            code__search__pb2.GetDomainsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.code_search.CodeSearchService/SearchEntities',
            code__search__pb2.SearchEntitiesRequest.SerializeToString,
            code__search__pb2.SearchEntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchSummaries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.code_search.CodeSearchService/SearchSummaries',
            code__search__pb2.SearchSummariesRequest.SerializeToString,
            code__search__pb2.SearchSummariesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCodeForEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.code_search.CodeSearchService/GetCodeForEntity',
            code__search__pb2.GetCodeForEntityRequest.SerializeToString,
            code__search__pb2.GetCodeForEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TraverseGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.code_search.CodeSearchService/TraverseGraph',
            code__search__pb2.TraverseGraphRequest.SerializeToString,
            code__search__pb2.TraverseGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntityGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.code_search.CodeSearchService/GetEntityGraph',
            code__search__pb2.GetEntityGraphRequest.SerializeToString,
            code__search__pb2.GetEntityGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FullSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.code_search.CodeSearchService/FullSearch',
            code__search__pb2.FullSearchRequest.SerializeToString,
            code__search__pb2.FullSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.code_search.CodeSearchService/Health',
            code__search__pb2.HealthRequest.SerializeToString,
            code__search__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
