# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import code_pb2 as code__pb2



class CodeServiceStub(object):
    """Code Management Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCode = channel.unary_unary(
                '/kgrag.code.CodeService/CreateCode',
                request_serializer=code__pb2.CreateCodeRequest.SerializeToString,
                response_deserializer=code__pb2.CreateCodeResponse.FromString,
                _registered_method=True)
        self.FindSimilarCode = channel.unary_unary(
                '/kgrag.code.CodeService/FindSimilarCode',
                request_serializer=code__pb2.FindSimilarCodeRequest.SerializeToString,
                response_deserializer=code__pb2.FindSimilarCodeResponse.FromString,
                _registered_method=True)
        self.AnalyzeImpact = channel.unary_unary(
                '/kgrag.code.CodeService/AnalyzeImpact',
                request_serializer=code__pb2.AnalyzeImpactRequest.SerializeToString,
                response_deserializer=code__pb2.AnalyzeImpactResponse.FromString,
                _registered_method=True)
        self.TraceExecutionFlow = channel.unary_unary(
                '/kgrag.code.CodeService/TraceExecutionFlow',
                request_serializer=code__pb2.TraceExecutionFlowRequest.SerializeToString,
                response_deserializer=code__pb2.TraceExecutionFlowResponse.FromString,
                _registered_method=True)


class CodeServiceServicer(object):
    """Code Management Service
    """

    def CreateCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindSimilarCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeImpact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TraceExecutionFlow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCode': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCode,
                    request_deserializer=code__pb2.CreateCodeRequest.FromString,
                    response_serializer=code__pb2.CreateCodeResponse.SerializeToString,
            ),
            'FindSimilarCode': grpc.unary_unary_rpc_method_handler(
                    servicer.FindSimilarCode,
                    request_deserializer=code__pb2.FindSimilarCodeRequest.FromString,
                    response_serializer=code__pb2.FindSimilarCodeResponse.SerializeToString,
            ),
            'AnalyzeImpact': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeImpact,
                    request_deserializer=code__pb2.AnalyzeImpactRequest.FromString,
                    response_serializer=code__pb2.AnalyzeImpactResponse.SerializeToString,
            ),
            'TraceExecutionFlow': grpc.unary_unary_rpc_method_handler(
                    servicer.TraceExecutionFlow,
                    request_deserializer=code__pb2.TraceExecutionFlowRequest.FromString,
                    response_serializer=code__pb2.TraceExecutionFlowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kgrag.code.CodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kgrag.code.CodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CodeService(object):
    """Code Management Service
    """

    @staticmethod
    def CreateCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.code.CodeService/CreateCode',
            code__pb2.CreateCodeRequest.SerializeToString,
            code__pb2.CreateCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindSimilarCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.code.CodeService/FindSimilarCode',
            code__pb2.FindSimilarCodeRequest.SerializeToString,
            code__pb2.FindSimilarCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeImpact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.code.CodeService/AnalyzeImpact',
            code__pb2.AnalyzeImpactRequest.SerializeToString,
            code__pb2.AnalyzeImpactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TraceExecutionFlow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.code.CodeService/TraceExecutionFlow',
            code__pb2.TraceExecutionFlowRequest.SerializeToString,
            code__pb2.TraceExecutionFlowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
