# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import document_search_pb2 as document__search__pb2



class DocumentSearchServiceStub(object):
    """Document Search Service — six deterministic primitives + Health.
    7 unary RPCs only. No LLM dependency on the backend.
    Agentic search runs in the MCP / CLI tool layer (T3 useBrain extension).

    Tenancy: company_id is derived server-side from the JWT. The client MUST NOT
    supply a company_id field — mirroring code_search.proto T10.A pattern.

    Knowledge is company-scoped (not project-scoped). Confirmed by probing cognee
    Neo4j 2026-04-29: source_node_set = "{company_id}_knowledge" (no project_id).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCollections = channel.unary_unary(
                '/kgrag.document_search.DocumentSearchService/GetCollections',
                request_serializer=document__search__pb2.GetCollectionsRequest.SerializeToString,
                response_deserializer=document__search__pb2.GetCollectionsResponse.FromString,
                _registered_method=True)
        self.SearchDocuments = channel.unary_unary(
                '/kgrag.document_search.DocumentSearchService/SearchDocuments',
                request_serializer=document__search__pb2.SearchDocumentsRequest.SerializeToString,
                response_deserializer=document__search__pb2.SearchDocumentsResponse.FromString,
                _registered_method=True)
        self.GetDocumentChunk = channel.unary_unary(
                '/kgrag.document_search.DocumentSearchService/GetDocumentChunk',
                request_serializer=document__search__pb2.GetDocumentChunkRequest.SerializeToString,
                response_deserializer=document__search__pb2.GetDocumentChunkResponse.FromString,
                _registered_method=True)
        self.SearchDocumentSummaries = channel.unary_unary(
                '/kgrag.document_search.DocumentSearchService/SearchDocumentSummaries',
                request_serializer=document__search__pb2.SearchDocumentSummariesRequest.SerializeToString,
                response_deserializer=document__search__pb2.SearchDocumentSummariesResponse.FromString,
                _registered_method=True)
        self.TraverseDocumentGraph = channel.unary_unary(
                '/kgrag.document_search.DocumentSearchService/TraverseDocumentGraph',
                request_serializer=document__search__pb2.TraverseDocumentGraphRequest.SerializeToString,
                response_deserializer=document__search__pb2.TraverseDocumentGraphResponse.FromString,
                _registered_method=True)
        self.FullDocumentSearch = channel.unary_unary(
                '/kgrag.document_search.DocumentSearchService/FullDocumentSearch',
                request_serializer=document__search__pb2.FullDocumentSearchRequest.SerializeToString,
                response_deserializer=document__search__pb2.FullDocumentSearchResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/kgrag.document_search.DocumentSearchService/Health',
                request_serializer=document__search__pb2.HealthRequest.SerializeToString,
                response_deserializer=document__search__pb2.HealthResponse.FromString,
                _registered_method=True)


class DocumentSearchServiceServicer(object):
    """Document Search Service — six deterministic primitives + Health.
    7 unary RPCs only. No LLM dependency on the backend.
    Agentic search runs in the MCP / CLI tool layer (T3 useBrain extension).

    Tenancy: company_id is derived server-side from the JWT. The client MUST NOT
    supply a company_id field — mirroring code_search.proto T10.A pattern.

    Knowledge is company-scoped (not project-scoped). Confirmed by probing cognee
    Neo4j 2026-04-29: source_node_set = "{company_id}_knowledge" (no project_id).
    """

    def GetCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocumentChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchDocumentSummaries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TraverseDocumentGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FullDocumentSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentSearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollections,
                    request_deserializer=document__search__pb2.GetCollectionsRequest.FromString,
                    response_serializer=document__search__pb2.GetCollectionsResponse.SerializeToString,
            ),
            'SearchDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchDocuments,
                    request_deserializer=document__search__pb2.SearchDocumentsRequest.FromString,
                    response_serializer=document__search__pb2.SearchDocumentsResponse.SerializeToString,
            ),
            'GetDocumentChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocumentChunk,
                    request_deserializer=document__search__pb2.GetDocumentChunkRequest.FromString,
                    response_serializer=document__search__pb2.GetDocumentChunkResponse.SerializeToString,
            ),
            'SearchDocumentSummaries': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchDocumentSummaries,
                    request_deserializer=document__search__pb2.SearchDocumentSummariesRequest.FromString,
                    response_serializer=document__search__pb2.SearchDocumentSummariesResponse.SerializeToString,
            ),
            'TraverseDocumentGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.TraverseDocumentGraph,
                    request_deserializer=document__search__pb2.TraverseDocumentGraphRequest.FromString,
                    response_serializer=document__search__pb2.TraverseDocumentGraphResponse.SerializeToString,
            ),
            'FullDocumentSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.FullDocumentSearch,
                    request_deserializer=document__search__pb2.FullDocumentSearchRequest.FromString,
                    response_serializer=document__search__pb2.FullDocumentSearchResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=document__search__pb2.HealthRequest.FromString,
                    response_serializer=document__search__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kgrag.document_search.DocumentSearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kgrag.document_search.DocumentSearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentSearchService(object):
    """Document Search Service — six deterministic primitives + Health.
    7 unary RPCs only. No LLM dependency on the backend.
    Agentic search runs in the MCP / CLI tool layer (T3 useBrain extension).

    Tenancy: company_id is derived server-side from the JWT. The client MUST NOT
    supply a company_id field — mirroring code_search.proto T10.A pattern.

    Knowledge is company-scoped (not project-scoped). Confirmed by probing cognee
    Neo4j 2026-04-29: source_node_set = "{company_id}_knowledge" (no project_id).
    """

    @staticmethod
    def GetCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.document_search.DocumentSearchService/GetCollections',
            document__search__pb2.GetCollectionsRequest.SerializeToString,
            document__search__pb2.GetCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.document_search.DocumentSearchService/SearchDocuments',
            document__search__pb2.SearchDocumentsRequest.SerializeToString,
            document__search__pb2.SearchDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocumentChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.document_search.DocumentSearchService/GetDocumentChunk',
            document__search__pb2.GetDocumentChunkRequest.SerializeToString,
            document__search__pb2.GetDocumentChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchDocumentSummaries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.document_search.DocumentSearchService/SearchDocumentSummaries',
            document__search__pb2.SearchDocumentSummariesRequest.SerializeToString,
            document__search__pb2.SearchDocumentSummariesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TraverseDocumentGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.document_search.DocumentSearchService/TraverseDocumentGraph',
            document__search__pb2.TraverseDocumentGraphRequest.SerializeToString,
            document__search__pb2.TraverseDocumentGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FullDocumentSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.document_search.DocumentSearchService/FullDocumentSearch',
            document__search__pb2.FullDocumentSearchRequest.SerializeToString,
            document__search__pb2.FullDocumentSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.document_search.DocumentSearchService/Health',
            document__search__pb2.HealthRequest.SerializeToString,
            document__search__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
