# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ingestion_pb2 as ingestion__pb2



class IngestionServiceStub(object):
    """Ingestion Service for querying code ingestion status and progress.
    Reads from MongoDB ingestions collection populated by the preprocessor.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIngestionStatus = channel.unary_unary(
                '/kgrag.ingestion.IngestionService/GetIngestionStatus',
                request_serializer=ingestion__pb2.GetIngestionStatusRequest.SerializeToString,
                response_deserializer=ingestion__pb2.GetIngestionStatusResponse.FromString,
                _registered_method=True)
        self.ListIngestions = channel.unary_unary(
                '/kgrag.ingestion.IngestionService/ListIngestions',
                request_serializer=ingestion__pb2.ListIngestionsRequest.SerializeToString,
                response_deserializer=ingestion__pb2.ListIngestionsResponse.FromString,
                _registered_method=True)


class IngestionServiceServicer(object):
    """Ingestion Service for querying code ingestion status and progress.
    Reads from MongoDB ingestions collection populated by the preprocessor.
    """

    def GetIngestionStatus(self, request, context):
        """Get status and progress of a specific ingestion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIngestions(self, request, context):
        """List ingestions for a project with optional filters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIngestionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIngestionStatus,
                    request_deserializer=ingestion__pb2.GetIngestionStatusRequest.FromString,
                    response_serializer=ingestion__pb2.GetIngestionStatusResponse.SerializeToString,
            ),
            'ListIngestions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIngestions,
                    request_deserializer=ingestion__pb2.ListIngestionsRequest.FromString,
                    response_serializer=ingestion__pb2.ListIngestionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kgrag.ingestion.IngestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kgrag.ingestion.IngestionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestionService(object):
    """Ingestion Service for querying code ingestion status and progress.
    Reads from MongoDB ingestions collection populated by the preprocessor.
    """

    @staticmethod
    def GetIngestionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.ingestion.IngestionService/GetIngestionStatus',
            ingestion__pb2.GetIngestionStatusRequest.SerializeToString,
            ingestion__pb2.GetIngestionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListIngestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kgrag.ingestion.IngestionService/ListIngestions',
            ingestion__pb2.ListIngestionsRequest.SerializeToString,
            ingestion__pb2.ListIngestionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
