# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kgrag_common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12kgrag_common.proto\x12\x0ckgrag.common\"W\n\rErrorResponse\x12\x10\n\x08is_error\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x12\n\nerror_code\x18\x03 \x01(\t\x12\x11\n\tretryable\x18\x04 \x01(\x08\"\xce\x01\n\x0bQueryResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x39\n\x08metadata\x18\x03 \x03(\x0b\x32\'.kgrag.common.QueryResult.MetadataEntry\x12\r\n\x05score\x18\x04 \x01(\x01\x12\x14\n\x0cvector_score\x18\x05 \x01(\x01\x12\x14\n\x0crerank_score\x18\x06 \x01(\x01\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kgrag_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYRESULT_METADATAENTRY']._loaded_options = None
  _globals['_QUERYRESULT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_ERRORRESPONSE']._serialized_start=36
  _globals['_ERRORRESPONSE']._serialized_end=123
  _globals['_QUERYRESULT']._serialized_start=126
  _globals['_QUERYRESULT']._serialized_end=332
  _globals['_QUERYRESULT_METADATAENTRY']._serialized_start=285
  _globals['_QUERYRESULT_METADATAENTRY']._serialized_end=332
# @@protoc_insertion_point(module_scope)
