"""File batching logic for optimized processing.

Groups files into batches based on size and token limits to minimize
API calls while respecting Gemini's context window.
"""

import fnmatch
from dataclasses import dataclass
from pathlib import Path

from loguru import logger

from .config import CodeServiceConfig


@dataclass
class CodeFile:
    """Represents a code file to be processed."""
    file_path: str
    content: str
    language: str


@dataclass
class Batch:
    """A batch of files to process together."""
    files: list[CodeFile]
    estimated_tokens: int


class BatchProcessor:
    """Handles file filtering and batching logic."""

    @staticmethod
    def should_process(file: CodeFile) -> bool:
        """Determine if file should be processed.

        Uses blocklist approach: process everything EXCEPT excluded extensions.

        Args:
            file: Code file to check

        Returns:
            True if file should be processed, False otherwise
        """
        # Check file size limits
        file_size = len(file.content.encode('utf-8'))
        if file_size < CodeServiceConfig.MIN_FILE_SIZE:
            logger.debug(f"Skipping {file.file_path} (too small: {file_size} bytes)")
            return False

        if file_size > CodeServiceConfig.MAX_FILE_SIZE:
            logger.warning(
                f"Skipping {file.file_path} (too large: {file_size} bytes)"
            )
            return False

        # Check skip patterns (simplified glob matching)
        for pattern in CodeServiceConfig.SKIP_PATTERNS:
            # Convert ** patterns to simpler checks
            pattern_simple = pattern.replace("**/", "").replace("/**", "")
            if pattern_simple in file.file_path:
                logger.debug(
                    f"Skipping {file.file_path} (matches pattern: {pattern})"
                )
                return False

        # Check for auto-generated markers
        content_lower = file.content.lower()
        auto_gen_markers = [
            "auto-generated",
            "autogenerated",
            "do not edit",
            "generated by",
            "code generated",
        ]

        for marker in auto_gen_markers:
            if marker in content_lower[:1000]:  # Check first 1000 chars
                logger.debug(
                    f"Skipping {file.file_path} (auto-generated)"
                )
                return False

        # Check exclusion list (blocklist approach)
        if CodeServiceConfig.is_excluded(file.file_path):
            logger.debug(
                f"Skipping {file.file_path} (excluded extension)"
            )
            return False

        # Language can be 'unknown' for files not in KNOWN_LANGUAGES
        # but not in EXCLUDED_EXTENSIONS - we still process them
        # (LLM will figure out what they are)

        return True

    @staticmethod
    def estimate_tokens(content: str) -> int:
        """Estimate token count for content.

        Uses simple heuristic: ~4 characters per token.

        Args:
            content: Text content

        Returns:
            Estimated token count
        """
        return len(content) // CodeServiceConfig.CHARS_PER_TOKEN

    @staticmethod
    def create_batches(files: list[CodeFile]) -> list[Batch]:
        """Create optimized batches from file list.

        Groups files into batches respecting token limits.
        For now, processes each file individually for simplicity.
        Future optimization: batch small files together.

        Args:
            files: List of code files to batch

        Returns:
            List of batches ready for processing
        """
        # Filter files first
        processable_files = [f for f in files if BatchProcessor.should_process(f)]

        logger.info(
            f"Batching: {len(processable_files)}/{len(files)} files "
            f"(skipped {len(files) - len(processable_files)})"
        )

        # For simplicity, create one batch per file
        # This is optimal for parallel processing and error isolation
        batches = []
        for file in processable_files:
            estimated_tokens = BatchProcessor.estimate_tokens(file.content)
            batches.append(
                Batch(
                    files=[file],
                    estimated_tokens=estimated_tokens
                )
            )

        logger.info(
            f"Created {len(batches)} batches "
            f"(avg {sum(b.estimated_tokens for b in batches) / len(batches):.0f} tokens/batch)"
            if batches else "Created 0 batches"
        )

        return batches

    @staticmethod
    def detect_language(file_path: str) -> str | None:
        """Detect programming language from file extension.

        Args:
            file_path: Path to the file

        Returns:
            Language name or None if unsupported
        """
        return CodeServiceConfig.get_language(file_path)