"""Pydantic models for API requests and responses."""

from api.models.company import CompanyCreate, CompanyResponse, CompanyListResponse
from api.models.project import (
    ProjectCreate,
    ProjectUpdate,
    ProjectTransferRequest,
    ProjectTransferResponse,
    ProjectResponse,
    ProjectListResponse,
    WebhookSecretResponse,
    ProjectInstructionsEmbedded,
)
from api.models.repository import RepositoryCreate, RepositoryResponse, RepositoryListResponse
from api.models.branch import BranchCreate, BranchResponse, BranchListResponse
from api.models.agent import (
    AgentCreate,
    AgentUpdate,
    AgentResponse,
    AgentListResponse,
    SkillChunkResponse,
    SkillChunkListResponse,
    AgentSearchQuery,
    AgentSearchResult,
    AgentSearchResponse,
)
from api.models.instructions import (
    CompanyInstructionsCreate,
    CompanyInstructionsResponse,
    ProjectInstructionsCreate,
    ProjectInstructionsResponse,
    ContextInstructionsResponse,
)
from api.models.task import (
    TaskCreate,
    TaskUpdate,
    TaskAssign,
    TaskResponse,
    TaskListResponse,
    ArtifactLink,
    ArtifactResponse,
    ArtifactListResponse,
)
from api.models.engagement import (
    EngagementCreate,
    EngagementUpdate,
    EngagementResponse,
    EngagementListResponse,
    EngagementWithEntriesResponse,
    EntryCreate,
    EntryUpdate,
    EntryResponse,
    EntryListResponse,
    EntryMetadata,
    EntrySearchRequest,
    EntrySearchResult,
    EntrySearchResponse,
    ResumeContextResponse,
)
from api.models.agent_skill import (
    LinkSkillRequest,
    SkillSectionResponse,
    SkillOverviewResponse,
    AgentSkillsResponse,
    LinkSkillResponse,
    UnlinkSkillResponse,
    CompanyInstructionsContext,
    ProjectInstructionsContext,
    AvailableAgentResponse,
    AgentContextResponse,
)
from api.models.knowledge import (
    KnowledgeCreate,
    KnowledgeResponse,
    KnowledgeQueryResponse,
    KnowledgeTagSearchResponse,
)
from api.models.lessons import (
    LessonCreate,
    LessonResponse,
    LessonQueryResponse,
    LessonQueryResult,
)
from api.models.delegation import (
    ProgressStep,
    DelegationStatusResponse,
    DelegationResultResponse,
    DelegationSummary,
    DelegationListResponse,
    CancelDelegationResponse,
)
from api.models.ingestion import (
    FailedFile,
    IngestionStatusResponse,
    IngestionSummary,
    IngestionListResponse,
)
from api.models.stats import CompanyStatsResponse
from api.models.agent_memory import (
    MemoryType,
    Category,
    SourceOrigin,
    StatusType,
    CreateMemoryRequest,
    UpdateMemoryRequest,
    QueryMemoriesRequest,
    LogStatusRequest,
    MemoryResponse,
    MemorySearchResult,
    MemorySearchResponse,
    MemoryListResponse,
    StatusLogResponse,
    StatusTimelineResponse,
)

__all__ = [
    "CompanyCreate",
    "CompanyResponse",
    "CompanyListResponse",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectTransferRequest",
    "ProjectTransferResponse",
    "ProjectResponse",
    "ProjectListResponse",
    "WebhookSecretResponse",
    "ProjectInstructionsEmbedded",
    "RepositoryCreate",
    "RepositoryResponse",
    "RepositoryListResponse",
    "BranchCreate",
    "BranchResponse",
    "BranchListResponse",
    "AgentCreate",
    "AgentUpdate",
    "AgentResponse",
    "AgentListResponse",
    "SkillChunkResponse",
    "SkillChunkListResponse",
    "AgentSearchQuery",
    "AgentSearchResult",
    "AgentSearchResponse",
    "CompanyInstructionsCreate",
    "CompanyInstructionsResponse",
    "ProjectInstructionsCreate",
    "ProjectInstructionsResponse",
    "ContextInstructionsResponse",
    "TaskCreate",
    "TaskUpdate",
    "TaskAssign",
    "TaskResponse",
    "TaskListResponse",
    "ArtifactLink",
    "ArtifactResponse",
    "ArtifactListResponse",
    "EngagementCreate",
    "EngagementUpdate",
    "EngagementResponse",
    "EngagementListResponse",
    "EngagementWithEntriesResponse",
    "EntryCreate",
    "EntryUpdate",
    "EntryResponse",
    "EntryListResponse",
    "EntryMetadata",
    "EntrySearchRequest",
    "EntrySearchResult",
    "EntrySearchResponse",
    "ResumeContextResponse",
    # Agent Skills
    "LinkSkillRequest",
    "SkillSectionResponse",
    "SkillOverviewResponse",
    "AgentSkillsResponse",
    "LinkSkillResponse",
    "UnlinkSkillResponse",
    "CompanyInstructionsContext",
    "ProjectInstructionsContext",
    "AvailableAgentResponse",
    "AgentContextResponse",
    # Knowledge
    "KnowledgeCreate",
    "KnowledgeResponse",
    "KnowledgeQueryResponse",
    "KnowledgeTagSearchResponse",
    # Lessons
    "LessonCreate",
    "LessonResponse",
    "LessonQueryResponse",
    "LessonQueryResult",
    # Delegations
    "ProgressStep",
    "DelegationStatusResponse",
    "DelegationResultResponse",
    "DelegationSummary",
    "DelegationListResponse",
    "CancelDelegationResponse",
    # Ingestions
    "FailedFile",
    "IngestionStatusResponse",
    "IngestionSummary",
    "IngestionListResponse",
    # Statistics
    "CompanyStatsResponse",
    # Agent Memory
    "MemoryType",
    "Category",
    "SourceOrigin",
    "StatusType",
    "CreateMemoryRequest",
    "UpdateMemoryRequest",
    "QueryMemoriesRequest",
    "LogStatusRequest",
    "MemoryResponse",
    "MemorySearchResult",
    "MemorySearchResponse",
    "MemoryListResponse",
    "StatusLogResponse",
    "StatusTimelineResponse",
]
